// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$665 {

    static final FunctionDescriptor g_file_enumerate_children_finish$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_enumerate_children_finish$MH = RuntimeHelper.downcallHandle(
        "g_file_enumerate_children_finish",
        constants$665.g_file_enumerate_children_finish$FUNC, false
    );
    static final FunctionDescriptor g_file_set_display_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_set_display_name$MH = RuntimeHelper.downcallHandle(
        "g_file_set_display_name",
        constants$665.g_file_set_display_name$FUNC, false
    );
    static final FunctionDescriptor g_file_set_display_name_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_set_display_name_async$MH = RuntimeHelper.downcallHandle(
        "g_file_set_display_name_async",
        constants$665.g_file_set_display_name_async$FUNC, false
    );
    static final FunctionDescriptor g_file_set_display_name_finish$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_set_display_name_finish$MH = RuntimeHelper.downcallHandle(
        "g_file_set_display_name_finish",
        constants$665.g_file_set_display_name_finish$FUNC, false
    );
    static final FunctionDescriptor g_file_delete$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_delete$MH = RuntimeHelper.downcallHandle(
        "g_file_delete",
        constants$665.g_file_delete$FUNC, false
    );
    static final FunctionDescriptor g_file_delete_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_delete_async$MH = RuntimeHelper.downcallHandle(
        "g_file_delete_async",
        constants$665.g_file_delete_async$FUNC, false
    );
}


