// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$24 {

    static final FunctionDescriptor g_intern_static_string$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_intern_static_string$MH = RuntimeHelper.downcallHandle(
        "g_intern_static_string",
        constants$24.g_intern_static_string$FUNC, false
    );
    static final FunctionDescriptor GErrorInitFunc$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GErrorInitFunc$MH = RuntimeHelper.downcallHandle(
        constants$24.GErrorInitFunc$FUNC, false
    );
    static final FunctionDescriptor GErrorCopyFunc$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GErrorCopyFunc$MH = RuntimeHelper.downcallHandle(
        constants$24.GErrorCopyFunc$FUNC, false
    );
    static final FunctionDescriptor GErrorClearFunc$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
}


