// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$258 {

    static final FunctionDescriptor g_rand_copy$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_rand_copy$MH = RuntimeHelper.downcallHandle(
        "g_rand_copy",
        constants$258.g_rand_copy$FUNC, false
    );
    static final FunctionDescriptor g_rand_set_seed$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_rand_set_seed$MH = RuntimeHelper.downcallHandle(
        "g_rand_set_seed",
        constants$258.g_rand_set_seed$FUNC, false
    );
    static final FunctionDescriptor g_rand_set_seed_array$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_rand_set_seed_array$MH = RuntimeHelper.downcallHandle(
        "g_rand_set_seed_array",
        constants$258.g_rand_set_seed_array$FUNC, false
    );
    static final FunctionDescriptor g_rand_int$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_rand_int$MH = RuntimeHelper.downcallHandle(
        "g_rand_int",
        constants$258.g_rand_int$FUNC, false
    );
    static final FunctionDescriptor g_rand_int_range$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_rand_int_range$MH = RuntimeHelper.downcallHandle(
        "g_rand_int_range",
        constants$258.g_rand_int_range$FUNC, false
    );
    static final FunctionDescriptor g_rand_double$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_rand_double$MH = RuntimeHelper.downcallHandle(
        "g_rand_double",
        constants$258.g_rand_double$FUNC, false
    );
}


