// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$89 {

    static final FunctionDescriptor g_bookmark_file_set_modified$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle g_bookmark_file_set_modified$MH = RuntimeHelper.downcallHandle(
        "g_bookmark_file_set_modified",
        constants$89.g_bookmark_file_set_modified$FUNC, false
    );
    static final FunctionDescriptor g_bookmark_file_set_modified_date_time$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_bookmark_file_set_modified_date_time$MH = RuntimeHelper.downcallHandle(
        "g_bookmark_file_set_modified_date_time",
        constants$89.g_bookmark_file_set_modified_date_time$FUNC, false
    );
    static final FunctionDescriptor g_bookmark_file_get_modified$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_bookmark_file_get_modified$MH = RuntimeHelper.downcallHandle(
        "g_bookmark_file_get_modified",
        constants$89.g_bookmark_file_get_modified$FUNC, false
    );
    static final FunctionDescriptor g_bookmark_file_get_modified_date_time$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_bookmark_file_get_modified_date_time$MH = RuntimeHelper.downcallHandle(
        "g_bookmark_file_get_modified_date_time",
        constants$89.g_bookmark_file_get_modified_date_time$FUNC, false
    );
    static final FunctionDescriptor g_bookmark_file_set_visited$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle g_bookmark_file_set_visited$MH = RuntimeHelper.downcallHandle(
        "g_bookmark_file_set_visited",
        constants$89.g_bookmark_file_set_visited$FUNC, false
    );
    static final FunctionDescriptor g_bookmark_file_set_visited_date_time$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_bookmark_file_set_visited_date_time$MH = RuntimeHelper.downcallHandle(
        "g_bookmark_file_set_visited_date_time",
        constants$89.g_bookmark_file_set_visited_date_time$FUNC, false
    );
}


