// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$334 {

    static final FunctionDescriptor g_uri_get_port$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_uri_get_port$MH = RuntimeHelper.downcallHandle(
        "g_uri_get_port",
        constants$334.g_uri_get_port$FUNC, false
    );
    static final FunctionDescriptor g_uri_get_path$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_uri_get_path$MH = RuntimeHelper.downcallHandle(
        "g_uri_get_path",
        constants$334.g_uri_get_path$FUNC, false
    );
    static final FunctionDescriptor g_uri_get_query$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_uri_get_query$MH = RuntimeHelper.downcallHandle(
        "g_uri_get_query",
        constants$334.g_uri_get_query$FUNC, false
    );
    static final FunctionDescriptor g_uri_get_fragment$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_uri_get_fragment$MH = RuntimeHelper.downcallHandle(
        "g_uri_get_fragment",
        constants$334.g_uri_get_fragment$FUNC, false
    );
    static final FunctionDescriptor g_uri_get_flags$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_uri_get_flags$MH = RuntimeHelper.downcallHandle(
        "g_uri_get_flags",
        constants$334.g_uri_get_flags$FUNC, false
    );
    static final FunctionDescriptor g_uri_parse_params$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_uri_parse_params$MH = RuntimeHelper.downcallHandle(
        "g_uri_parse_params",
        constants$334.g_uri_parse_params$FUNC, false
    );
}


