// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$927 {

    static final FunctionDescriptor glib_autoptr_clear_GMenuLinkIter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GMenuLinkIter$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GMenuLinkIter",
        constants$927.glib_autoptr_clear_GMenuLinkIter$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GMenuLinkIter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GMenuLinkIter$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GMenuLinkIter",
        constants$927.glib_autoptr_cleanup_GMenuLinkIter$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GMenuLinkIter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GMenuLinkIter$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GMenuLinkIter",
        constants$927.glib_listautoptr_cleanup_GMenuLinkIter$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GMenuLinkIter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GMenuLinkIter$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GMenuLinkIter",
        constants$927.glib_slistautoptr_cleanup_GMenuLinkIter$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GMenuLinkIter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GMenuLinkIter$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GMenuLinkIter",
        constants$927.glib_queueautoptr_cleanup_GMenuLinkIter$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GMount$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GMount$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GMount",
        constants$927.glib_autoptr_clear_GMount$FUNC, false
    );
}


