// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$744 {

    static final FunctionDescriptor g_menu_append$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_menu_append$MH = RuntimeHelper.downcallHandle(
        "g_menu_append",
        constants$744.g_menu_append$FUNC, false
    );
    static final FunctionDescriptor g_menu_insert_section$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_menu_insert_section$MH = RuntimeHelper.downcallHandle(
        "g_menu_insert_section",
        constants$744.g_menu_insert_section$FUNC, false
    );
    static final FunctionDescriptor g_menu_prepend_section$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_menu_prepend_section$MH = RuntimeHelper.downcallHandle(
        "g_menu_prepend_section",
        constants$744.g_menu_prepend_section$FUNC, false
    );
    static final FunctionDescriptor g_menu_append_section$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_menu_append_section$MH = RuntimeHelper.downcallHandle(
        "g_menu_append_section",
        constants$744.g_menu_append_section$FUNC, false
    );
    static final FunctionDescriptor g_menu_insert_submenu$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_menu_insert_submenu$MH = RuntimeHelper.downcallHandle(
        "g_menu_insert_submenu",
        constants$744.g_menu_insert_submenu$FUNC, false
    );
    static final FunctionDescriptor g_menu_prepend_submenu$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_menu_prepend_submenu$MH = RuntimeHelper.downcallHandle(
        "g_menu_prepend_submenu",
        constants$744.g_menu_prepend_submenu$FUNC, false
    );
}


