// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$592 {

    static final FunctionDescriptor g_dbus_connection_new_finish$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_connection_new_finish$MH = RuntimeHelper.downcallHandle(
        "g_dbus_connection_new_finish",
        constants$592.g_dbus_connection_new_finish$FUNC, false
    );
    static final FunctionDescriptor g_dbus_connection_new_sync$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_connection_new_sync$MH = RuntimeHelper.downcallHandle(
        "g_dbus_connection_new_sync",
        constants$592.g_dbus_connection_new_sync$FUNC, false
    );
    static final FunctionDescriptor g_dbus_connection_new_for_address$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_connection_new_for_address$MH = RuntimeHelper.downcallHandle(
        "g_dbus_connection_new_for_address",
        constants$592.g_dbus_connection_new_for_address$FUNC, false
    );
    static final FunctionDescriptor g_dbus_connection_new_for_address_finish$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_connection_new_for_address_finish$MH = RuntimeHelper.downcallHandle(
        "g_dbus_connection_new_for_address_finish",
        constants$592.g_dbus_connection_new_for_address_finish$FUNC, false
    );
    static final FunctionDescriptor g_dbus_connection_new_for_address_sync$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_connection_new_for_address_sync$MH = RuntimeHelper.downcallHandle(
        "g_dbus_connection_new_for_address_sync",
        constants$592.g_dbus_connection_new_for_address_sync$FUNC, false
    );
    static final FunctionDescriptor g_dbus_connection_start_message_processing$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_connection_start_message_processing$MH = RuntimeHelper.downcallHandle(
        "g_dbus_connection_start_message_processing",
        constants$592.g_dbus_connection_start_message_processing$FUNC, false
    );
}


