// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$773 {

    static final FunctionDescriptor g_proxy_address_get_destination_hostname$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_proxy_address_get_destination_hostname$MH = RuntimeHelper.downcallHandle(
        "g_proxy_address_get_destination_hostname",
        constants$773.g_proxy_address_get_destination_hostname$FUNC, false
    );
    static final FunctionDescriptor g_proxy_address_get_destination_port$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_proxy_address_get_destination_port$MH = RuntimeHelper.downcallHandle(
        "g_proxy_address_get_destination_port",
        constants$773.g_proxy_address_get_destination_port$FUNC, false
    );
    static final FunctionDescriptor g_proxy_address_get_username$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_proxy_address_get_username$MH = RuntimeHelper.downcallHandle(
        "g_proxy_address_get_username",
        constants$773.g_proxy_address_get_username$FUNC, false
    );
    static final FunctionDescriptor g_proxy_address_get_password$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_proxy_address_get_password$MH = RuntimeHelper.downcallHandle(
        "g_proxy_address_get_password",
        constants$773.g_proxy_address_get_password$FUNC, false
    );
    static final FunctionDescriptor g_proxy_address_get_uri$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_proxy_address_get_uri$MH = RuntimeHelper.downcallHandle(
        "g_proxy_address_get_uri",
        constants$773.g_proxy_address_get_uri$FUNC, false
    );
    static final FunctionDescriptor g_socket_address_enumerator_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_socket_address_enumerator_get_type$MH = RuntimeHelper.downcallHandle(
        "g_socket_address_enumerator_get_type",
        constants$773.g_socket_address_enumerator_get_type$FUNC, false
    );
}


