// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$132 {

    static final FunctionDescriptor g_list_remove_link$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_list_remove_link$MH = RuntimeHelper.downcallHandle(
        "g_list_remove_link",
        constants$132.g_list_remove_link$FUNC, false
    );
    static final FunctionDescriptor g_list_delete_link$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_list_delete_link$MH = RuntimeHelper.downcallHandle(
        "g_list_delete_link",
        constants$132.g_list_delete_link$FUNC, false
    );
    static final FunctionDescriptor g_list_reverse$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_list_reverse$MH = RuntimeHelper.downcallHandle(
        "g_list_reverse",
        constants$132.g_list_reverse$FUNC, false
    );
    static final FunctionDescriptor g_list_copy$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_list_copy$MH = RuntimeHelper.downcallHandle(
        "g_list_copy",
        constants$132.g_list_copy$FUNC, false
    );
    static final FunctionDescriptor g_list_copy_deep$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_list_copy_deep$MH = RuntimeHelper.downcallHandle(
        "g_list_copy_deep",
        constants$132.g_list_copy_deep$FUNC, false
    );
    static final FunctionDescriptor g_list_nth$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_list_nth$MH = RuntimeHelper.downcallHandle(
        "g_list_nth",
        constants$132.g_list_nth$FUNC, false
    );
}


