// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$269 {

    static final FunctionDescriptor g_regex_replace_eval$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_regex_replace_eval$MH = RuntimeHelper.downcallHandle(
        "g_regex_replace_eval",
        constants$269.g_regex_replace_eval$FUNC, false
    );
    static final FunctionDescriptor g_regex_check_replacement$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_regex_check_replacement$MH = RuntimeHelper.downcallHandle(
        "g_regex_check_replacement",
        constants$269.g_regex_check_replacement$FUNC, false
    );
    static final FunctionDescriptor g_match_info_get_regex$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_match_info_get_regex$MH = RuntimeHelper.downcallHandle(
        "g_match_info_get_regex",
        constants$269.g_match_info_get_regex$FUNC, false
    );
    static final FunctionDescriptor g_match_info_get_string$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_match_info_get_string$MH = RuntimeHelper.downcallHandle(
        "g_match_info_get_string",
        constants$269.g_match_info_get_string$FUNC, false
    );
    static final FunctionDescriptor g_match_info_ref$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_match_info_ref$MH = RuntimeHelper.downcallHandle(
        "g_match_info_ref",
        constants$269.g_match_info_ref$FUNC, false
    );
    static final FunctionDescriptor g_match_info_unref$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_match_info_unref$MH = RuntimeHelper.downcallHandle(
        "g_match_info_unref",
        constants$269.g_match_info_unref$FUNC, false
    );
}


