// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$306 {

    static final FunctionDescriptor g_string_chunk_insert_const$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_string_chunk_insert_const$MH = RuntimeHelper.downcallHandle(
        "g_string_chunk_insert_const",
        constants$306.g_string_chunk_insert_const$FUNC, false
    );
    static final FunctionDescriptor g_strv_builder_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle g_strv_builder_new$MH = RuntimeHelper.downcallHandle(
        "g_strv_builder_new",
        constants$306.g_strv_builder_new$FUNC, false
    );
    static final FunctionDescriptor g_strv_builder_unref$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_strv_builder_unref$MH = RuntimeHelper.downcallHandle(
        "g_strv_builder_unref",
        constants$306.g_strv_builder_unref$FUNC, false
    );
    static final FunctionDescriptor g_strv_builder_ref$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_strv_builder_ref$MH = RuntimeHelper.downcallHandle(
        "g_strv_builder_ref",
        constants$306.g_strv_builder_ref$FUNC, false
    );
    static final FunctionDescriptor g_strv_builder_add$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_strv_builder_add$MH = RuntimeHelper.downcallHandle(
        "g_strv_builder_add",
        constants$306.g_strv_builder_add$FUNC, false
    );
    static final FunctionDescriptor g_strv_builder_addv$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_strv_builder_addv$MH = RuntimeHelper.downcallHandle(
        "g_strv_builder_addv",
        constants$306.g_strv_builder_addv$FUNC, false
    );
}


