// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$476 {

    static final FunctionDescriptor g_object_remove_weak_pointer$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_object_remove_weak_pointer$MH = RuntimeHelper.downcallHandle(
        "g_object_remove_weak_pointer",
        constants$476.g_object_remove_weak_pointer$FUNC, false
    );
    static final FunctionDescriptor GToggleNotify$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle GToggleNotify$MH = RuntimeHelper.downcallHandle(
        constants$476.GToggleNotify$FUNC, false
    );
    static final FunctionDescriptor g_object_add_toggle_ref$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_object_add_toggle_ref$MH = RuntimeHelper.downcallHandle(
        "g_object_add_toggle_ref",
        constants$476.g_object_add_toggle_ref$FUNC, false
    );
    static final FunctionDescriptor g_object_remove_toggle_ref$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_object_remove_toggle_ref$MH = RuntimeHelper.downcallHandle(
        "g_object_remove_toggle_ref",
        constants$476.g_object_remove_toggle_ref$FUNC, false
    );
    static final FunctionDescriptor g_object_get_qdata$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_object_get_qdata$MH = RuntimeHelper.downcallHandle(
        "g_object_get_qdata",
        constants$476.g_object_get_qdata$FUNC, false
    );
}


