// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$711 {

    static final FunctionDescriptor g_ask_password_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_ask_password_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "g_ask_password_flags_get_type",
        constants$711.g_ask_password_flags_get_type$FUNC, false
    );
    static final FunctionDescriptor g_password_save_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_password_save_get_type$MH = RuntimeHelper.downcallHandle(
        "g_password_save_get_type",
        constants$711.g_password_save_get_type$FUNC, false
    );
    static final FunctionDescriptor g_mount_operation_result_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_mount_operation_result_get_type$MH = RuntimeHelper.downcallHandle(
        "g_mount_operation_result_get_type",
        constants$711.g_mount_operation_result_get_type$FUNC, false
    );
    static final FunctionDescriptor g_output_stream_splice_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_output_stream_splice_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "g_output_stream_splice_flags_get_type",
        constants$711.g_output_stream_splice_flags_get_type$FUNC, false
    );
    static final FunctionDescriptor g_io_stream_splice_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_io_stream_splice_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "g_io_stream_splice_flags_get_type",
        constants$711.g_io_stream_splice_flags_get_type$FUNC, false
    );
    static final FunctionDescriptor g_emblem_origin_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_emblem_origin_get_type$MH = RuntimeHelper.downcallHandle(
        "g_emblem_origin_get_type",
        constants$711.g_emblem_origin_get_type$FUNC, false
    );
}


