// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$229 {

    static final FunctionDescriptor g_variant_iter_init$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_iter_init$MH = RuntimeHelper.downcallHandle(
        "g_variant_iter_init",
        constants$229.g_variant_iter_init$FUNC, false
    );
    static final FunctionDescriptor g_variant_iter_copy$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_iter_copy$MH = RuntimeHelper.downcallHandle(
        "g_variant_iter_copy",
        constants$229.g_variant_iter_copy$FUNC, false
    );
    static final FunctionDescriptor g_variant_iter_n_children$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_iter_n_children$MH = RuntimeHelper.downcallHandle(
        "g_variant_iter_n_children",
        constants$229.g_variant_iter_n_children$FUNC, false
    );
    static final FunctionDescriptor g_variant_iter_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_iter_free$MH = RuntimeHelper.downcallHandle(
        "g_variant_iter_free",
        constants$229.g_variant_iter_free$FUNC, false
    );
    static final FunctionDescriptor g_variant_iter_next_value$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_iter_next_value$MH = RuntimeHelper.downcallHandle(
        "g_variant_iter_next_value",
        constants$229.g_variant_iter_next_value$FUNC, false
    );
    static final FunctionDescriptor g_variant_iter_next$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_iter_next$MH = RuntimeHelper.downcallHandle(
        "g_variant_iter_next",
        constants$229.g_variant_iter_next$FUNC, true
    );
}


