// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$714 {

    static final FunctionDescriptor g_bus_name_owner_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_bus_name_owner_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "g_bus_name_owner_flags_get_type",
        constants$714.g_bus_name_owner_flags_get_type$FUNC, false
    );
    static final FunctionDescriptor g_bus_name_watcher_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_bus_name_watcher_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "g_bus_name_watcher_flags_get_type",
        constants$714.g_bus_name_watcher_flags_get_type$FUNC, false
    );
    static final FunctionDescriptor g_dbus_proxy_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_dbus_proxy_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "g_dbus_proxy_flags_get_type",
        constants$714.g_dbus_proxy_flags_get_type$FUNC, false
    );
    static final FunctionDescriptor g_dbus_error_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_dbus_error_get_type$MH = RuntimeHelper.downcallHandle(
        "g_dbus_error_get_type",
        constants$714.g_dbus_error_get_type$FUNC, false
    );
    static final FunctionDescriptor g_dbus_connection_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_dbus_connection_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "g_dbus_connection_flags_get_type",
        constants$714.g_dbus_connection_flags_get_type$FUNC, false
    );
    static final FunctionDescriptor g_dbus_capability_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_dbus_capability_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "g_dbus_capability_flags_get_type",
        constants$714.g_dbus_capability_flags_get_type$FUNC, false
    );
}


