// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$491 {

    static final FunctionDescriptor g_param_spec_boxed$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_param_spec_boxed$MH = RuntimeHelper.downcallHandle(
        "g_param_spec_boxed",
        constants$491.g_param_spec_boxed$FUNC, false
    );
    static final FunctionDescriptor g_param_spec_pointer$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_param_spec_pointer$MH = RuntimeHelper.downcallHandle(
        "g_param_spec_pointer",
        constants$491.g_param_spec_pointer$FUNC, false
    );
    static final FunctionDescriptor g_param_spec_value_array$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_param_spec_value_array$MH = RuntimeHelper.downcallHandle(
        "g_param_spec_value_array",
        constants$491.g_param_spec_value_array$FUNC, false
    );
    static final FunctionDescriptor g_param_spec_object$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_param_spec_object$MH = RuntimeHelper.downcallHandle(
        "g_param_spec_object",
        constants$491.g_param_spec_object$FUNC, false
    );
    static final FunctionDescriptor g_param_spec_override$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_param_spec_override$MH = RuntimeHelper.downcallHandle(
        "g_param_spec_override",
        constants$491.g_param_spec_override$FUNC, false
    );
    static final FunctionDescriptor g_param_spec_gtype$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_param_spec_gtype$MH = RuntimeHelper.downcallHandle(
        "g_param_spec_gtype",
        constants$491.g_param_spec_gtype$FUNC, false
    );
}


