// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$394 {

    static final FunctionDescriptor glib_listautoptr_cleanup_GNode$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GNode$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GNode",
        constants$394.glib_listautoptr_cleanup_GNode$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GNode$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GNode$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GNode",
        constants$394.glib_slistautoptr_cleanup_GNode$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GNode$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GNode$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GNode",
        constants$394.glib_queueautoptr_cleanup_GNode$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GOptionContext$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GOptionContext$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GOptionContext",
        constants$394.glib_autoptr_clear_GOptionContext$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GOptionContext$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GOptionContext$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GOptionContext",
        constants$394.glib_autoptr_cleanup_GOptionContext$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GOptionContext$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GOptionContext$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GOptionContext",
        constants$394.glib_listautoptr_cleanup_GOptionContext$FUNC, false
    );
}


