// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$962 {

    static final FunctionDescriptor glib_autoptr_clear_GTask$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GTask$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GTask",
        constants$962.glib_autoptr_clear_GTask$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GTask$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GTask$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GTask",
        constants$962.glib_autoptr_cleanup_GTask$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GTask$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GTask$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GTask",
        constants$962.glib_listautoptr_cleanup_GTask$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GTask$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GTask$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GTask",
        constants$962.glib_slistautoptr_cleanup_GTask$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GTask$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GTask$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GTask",
        constants$962.glib_queueautoptr_cleanup_GTask$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GTcpConnection$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GTcpConnection$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GTcpConnection",
        constants$962.glib_autoptr_clear_GTcpConnection$FUNC, false
    );
}


