// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$875 {

    static final FunctionDescriptor glib_slistautoptr_cleanup_GApplicationCommandLine$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GApplicationCommandLine$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GApplicationCommandLine",
        constants$875.glib_slistautoptr_cleanup_GApplicationCommandLine$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GApplicationCommandLine$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GApplicationCommandLine$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GApplicationCommandLine",
        constants$875.glib_queueautoptr_cleanup_GApplicationCommandLine$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GApplication$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GApplication$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GApplication",
        constants$875.glib_autoptr_clear_GApplication$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GApplication$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GApplication$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GApplication",
        constants$875.glib_autoptr_cleanup_GApplication$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GApplication$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GApplication$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GApplication",
        constants$875.glib_listautoptr_cleanup_GApplication$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GApplication$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GApplication$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GApplication",
        constants$875.glib_slistautoptr_cleanup_GApplication$FUNC, false
    );
}


