// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$621 {

    static final FunctionDescriptor g_dbus_method_invocation_get_interface_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_method_invocation_get_interface_name$MH = RuntimeHelper.downcallHandle(
        "g_dbus_method_invocation_get_interface_name",
        constants$621.g_dbus_method_invocation_get_interface_name$FUNC, false
    );
    static final FunctionDescriptor g_dbus_method_invocation_get_method_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_method_invocation_get_method_name$MH = RuntimeHelper.downcallHandle(
        "g_dbus_method_invocation_get_method_name",
        constants$621.g_dbus_method_invocation_get_method_name$FUNC, false
    );
    static final FunctionDescriptor g_dbus_method_invocation_get_method_info$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_method_invocation_get_method_info$MH = RuntimeHelper.downcallHandle(
        "g_dbus_method_invocation_get_method_info",
        constants$621.g_dbus_method_invocation_get_method_info$FUNC, false
    );
    static final FunctionDescriptor g_dbus_method_invocation_get_property_info$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_method_invocation_get_property_info$MH = RuntimeHelper.downcallHandle(
        "g_dbus_method_invocation_get_property_info",
        constants$621.g_dbus_method_invocation_get_property_info$FUNC, false
    );
    static final FunctionDescriptor g_dbus_method_invocation_get_connection$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_method_invocation_get_connection$MH = RuntimeHelper.downcallHandle(
        "g_dbus_method_invocation_get_connection",
        constants$621.g_dbus_method_invocation_get_connection$FUNC, false
    );
    static final FunctionDescriptor g_dbus_method_invocation_get_message$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_method_invocation_get_message$MH = RuntimeHelper.downcallHandle(
        "g_dbus_method_invocation_get_message",
        constants$621.g_dbus_method_invocation_get_message$FUNC, false
    );
}


