// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$906 {

    static final FunctionDescriptor glib_queueautoptr_cleanup_GFile$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GFile$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GFile",
        constants$906.glib_queueautoptr_cleanup_GFile$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GFileAttributeInfoList$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GFileAttributeInfoList$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GFileAttributeInfoList",
        constants$906.glib_autoptr_clear_GFileAttributeInfoList$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GFileAttributeInfoList$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GFileAttributeInfoList$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GFileAttributeInfoList",
        constants$906.glib_autoptr_cleanup_GFileAttributeInfoList$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GFileAttributeInfoList$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GFileAttributeInfoList$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GFileAttributeInfoList",
        constants$906.glib_listautoptr_cleanup_GFileAttributeInfoList$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GFileAttributeInfoList$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GFileAttributeInfoList$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GFileAttributeInfoList",
        constants$906.glib_slistautoptr_cleanup_GFileAttributeInfoList$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GFileAttributeInfoList$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GFileAttributeInfoList$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GFileAttributeInfoList",
        constants$906.glib_queueautoptr_cleanup_GFileAttributeInfoList$FUNC, false
    );
}


