// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$382 {

    static final FunctionDescriptor glib_autoptr_clear_GHashTable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GHashTable$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GHashTable",
        constants$382.glib_autoptr_clear_GHashTable$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GHashTable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GHashTable$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GHashTable",
        constants$382.glib_autoptr_cleanup_GHashTable$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GHashTable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GHashTable$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GHashTable",
        constants$382.glib_listautoptr_cleanup_GHashTable$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GHashTable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GHashTable$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GHashTable",
        constants$382.glib_slistautoptr_cleanup_GHashTable$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GHashTable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GHashTable$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GHashTable",
        constants$382.glib_queueautoptr_cleanup_GHashTable$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GHmac$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GHmac$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GHmac",
        constants$382.glib_autoptr_clear_GHmac$FUNC, false
    );
}


