// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$935 {

    static final FunctionDescriptor glib_slistautoptr_cleanup_GPermission$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GPermission$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GPermission",
        constants$935.glib_slistautoptr_cleanup_GPermission$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GPermission$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GPermission$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GPermission",
        constants$935.glib_queueautoptr_cleanup_GPermission$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GPollableInputStream$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GPollableInputStream$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GPollableInputStream",
        constants$935.glib_autoptr_clear_GPollableInputStream$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GPollableInputStream$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GPollableInputStream$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GPollableInputStream",
        constants$935.glib_autoptr_cleanup_GPollableInputStream$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GPollableInputStream$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GPollableInputStream$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GPollableInputStream",
        constants$935.glib_listautoptr_cleanup_GPollableInputStream$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GPollableInputStream$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GPollableInputStream$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GPollableInputStream",
        constants$935.glib_slistautoptr_cleanup_GPollableInputStream$FUNC, false
    );
}


