// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$198 {

    static final  GroupLayout g_io_watch_funcs$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("prepare"),
        Constants$root.C_POINTER$LAYOUT.withName("check"),
        Constants$root.C_POINTER$LAYOUT.withName("dispatch"),
        Constants$root.C_POINTER$LAYOUT.withName("finalize"),
        Constants$root.C_POINTER$LAYOUT.withName("closure_callback"),
        Constants$root.C_POINTER$LAYOUT.withName("closure_marshal")
    ).withName("_GSourceFuncs");
    static final MemorySegment g_io_watch_funcs$SEGMENT = RuntimeHelper.lookupGlobalVariable("g_io_watch_funcs", constants$198.g_io_watch_funcs$LAYOUT);
    static final FunctionDescriptor g_key_file_error_quark$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle g_key_file_error_quark$MH = RuntimeHelper.downcallHandle(
        "g_key_file_error_quark",
        constants$198.g_key_file_error_quark$FUNC, false
    );
    static final FunctionDescriptor g_key_file_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle g_key_file_new$MH = RuntimeHelper.downcallHandle(
        "g_key_file_new",
        constants$198.g_key_file_new$FUNC, false
    );
    static final FunctionDescriptor g_key_file_ref$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_key_file_ref$MH = RuntimeHelper.downcallHandle(
        "g_key_file_ref",
        constants$198.g_key_file_ref$FUNC, false
    );
    static final FunctionDescriptor g_key_file_unref$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_key_file_unref$MH = RuntimeHelper.downcallHandle(
        "g_key_file_unref",
        constants$198.g_key_file_unref$FUNC, false
    );
    static final FunctionDescriptor g_key_file_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_key_file_free$MH = RuntimeHelper.downcallHandle(
        "g_key_file_free",
        constants$198.g_key_file_free$FUNC, false
    );
}


