// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$558 {

    static final FunctionDescriptor g_content_type_equals$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_content_type_equals$MH = RuntimeHelper.downcallHandle(
        "g_content_type_equals",
        constants$558.g_content_type_equals$FUNC, false
    );
    static final FunctionDescriptor g_content_type_is_a$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_content_type_is_a$MH = RuntimeHelper.downcallHandle(
        "g_content_type_is_a",
        constants$558.g_content_type_is_a$FUNC, false
    );
    static final FunctionDescriptor g_content_type_is_mime_type$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_content_type_is_mime_type$MH = RuntimeHelper.downcallHandle(
        "g_content_type_is_mime_type",
        constants$558.g_content_type_is_mime_type$FUNC, false
    );
    static final FunctionDescriptor g_content_type_is_unknown$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_content_type_is_unknown$MH = RuntimeHelper.downcallHandle(
        "g_content_type_is_unknown",
        constants$558.g_content_type_is_unknown$FUNC, false
    );
    static final FunctionDescriptor g_content_type_get_description$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_content_type_get_description$MH = RuntimeHelper.downcallHandle(
        "g_content_type_get_description",
        constants$558.g_content_type_get_description$FUNC, false
    );
    static final FunctionDescriptor g_content_type_get_mime_type$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_content_type_get_mime_type$MH = RuntimeHelper.downcallHandle(
        "g_content_type_get_mime_type",
        constants$558.g_content_type_get_mime_type$FUNC, false
    );
}


