// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$456 {

    static final FunctionDescriptor g_signal_list_ids$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_signal_list_ids$MH = RuntimeHelper.downcallHandle(
        "g_signal_list_ids",
        constants$456.g_signal_list_ids$FUNC, false
    );
    static final FunctionDescriptor g_signal_is_valid_name$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_signal_is_valid_name$MH = RuntimeHelper.downcallHandle(
        "g_signal_is_valid_name",
        constants$456.g_signal_is_valid_name$FUNC, false
    );
    static final FunctionDescriptor g_signal_parse_name$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_signal_parse_name$MH = RuntimeHelper.downcallHandle(
        "g_signal_parse_name",
        constants$456.g_signal_parse_name$FUNC, false
    );
    static final FunctionDescriptor g_signal_get_invocation_hint$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_signal_get_invocation_hint$MH = RuntimeHelper.downcallHandle(
        "g_signal_get_invocation_hint",
        constants$456.g_signal_get_invocation_hint$FUNC, false
    );
    static final FunctionDescriptor g_signal_stop_emission$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_signal_stop_emission$MH = RuntimeHelper.downcallHandle(
        "g_signal_stop_emission",
        constants$456.g_signal_stop_emission$FUNC, false
    );
    static final FunctionDescriptor g_signal_stop_emission_by_name$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_signal_stop_emission_by_name$MH = RuntimeHelper.downcallHandle(
        "g_signal_stop_emission_by_name",
        constants$456.g_signal_stop_emission_by_name$FUNC, false
    );
}


