// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$378 {

    static final FunctionDescriptor glib_autoptr_cleanup_GChecksum$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GChecksum$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GChecksum",
        constants$378.glib_autoptr_cleanup_GChecksum$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GChecksum$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GChecksum$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GChecksum",
        constants$378.glib_listautoptr_cleanup_GChecksum$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GChecksum$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GChecksum$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GChecksum",
        constants$378.glib_slistautoptr_cleanup_GChecksum$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GChecksum$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GChecksum$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GChecksum",
        constants$378.glib_queueautoptr_cleanup_GChecksum$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GDateTime$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GDateTime$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GDateTime",
        constants$378.glib_autoptr_clear_GDateTime$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GDateTime$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GDateTime$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GDateTime",
        constants$378.glib_autoptr_cleanup_GDateTime$FUNC, false
    );
}


