// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$70 {

    static final FunctionDescriptor pthread_sigmask$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pthread_sigmask$MH = RuntimeHelper.downcallHandle(
        "pthread_sigmask",
        constants$70.pthread_sigmask$FUNC, false
    );
    static final FunctionDescriptor pthread_kill$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle pthread_kill$MH = RuntimeHelper.downcallHandle(
        "pthread_kill",
        constants$70.pthread_kill$FUNC, false
    );
    static final FunctionDescriptor __libc_current_sigrtmin$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle __libc_current_sigrtmin$MH = RuntimeHelper.downcallHandle(
        "__libc_current_sigrtmin",
        constants$70.__libc_current_sigrtmin$FUNC, false
    );
    static final FunctionDescriptor __libc_current_sigrtmax$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle __libc_current_sigrtmax$MH = RuntimeHelper.downcallHandle(
        "__libc_current_sigrtmax",
        constants$70.__libc_current_sigrtmax$FUNC, false
    );
    static final FunctionDescriptor g_on_error_query$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_on_error_query$MH = RuntimeHelper.downcallHandle(
        "g_on_error_query",
        constants$70.g_on_error_query$FUNC, false
    );
    static final FunctionDescriptor g_on_error_stack_trace$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_on_error_stack_trace$MH = RuntimeHelper.downcallHandle(
        "g_on_error_stack_trace",
        constants$70.g_on_error_stack_trace$FUNC, false
    );
}


