// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$406 {

    static final FunctionDescriptor glib_slistautoptr_cleanup_GThread$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GThread$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GThread",
        constants$406.glib_slistautoptr_cleanup_GThread$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GThread$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GThread$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GThread",
        constants$406.glib_queueautoptr_cleanup_GThread$FUNC, false
    );
    static final FunctionDescriptor glib_auto_cleanup_GMutex$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_auto_cleanup_GMutex$MH = RuntimeHelper.downcallHandle(
        "glib_auto_cleanup_GMutex",
        constants$406.glib_auto_cleanup_GMutex$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GMutexLocker$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GMutexLocker$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GMutexLocker",
        constants$406.glib_autoptr_clear_GMutexLocker$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GMutexLocker$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GMutexLocker$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GMutexLocker",
        constants$406.glib_autoptr_cleanup_GMutexLocker$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GMutexLocker$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GMutexLocker$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GMutexLocker",
        constants$406.glib_listautoptr_cleanup_GMutexLocker$FUNC, false
    );
}


