// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$370 {

    static final FunctionDescriptor g_static_rec_mutex_init$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_static_rec_mutex_init$MH = RuntimeHelper.downcallHandle(
        "g_static_rec_mutex_init",
        constants$370.g_static_rec_mutex_init$FUNC, false
    );
    static final FunctionDescriptor g_static_rec_mutex_lock$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_static_rec_mutex_lock$MH = RuntimeHelper.downcallHandle(
        "g_static_rec_mutex_lock",
        constants$370.g_static_rec_mutex_lock$FUNC, false
    );
    static final FunctionDescriptor g_static_rec_mutex_trylock$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_static_rec_mutex_trylock$MH = RuntimeHelper.downcallHandle(
        "g_static_rec_mutex_trylock",
        constants$370.g_static_rec_mutex_trylock$FUNC, false
    );
    static final FunctionDescriptor g_static_rec_mutex_unlock$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_static_rec_mutex_unlock$MH = RuntimeHelper.downcallHandle(
        "g_static_rec_mutex_unlock",
        constants$370.g_static_rec_mutex_unlock$FUNC, false
    );
    static final FunctionDescriptor g_static_rec_mutex_lock_full$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_static_rec_mutex_lock_full$MH = RuntimeHelper.downcallHandle(
        "g_static_rec_mutex_lock_full",
        constants$370.g_static_rec_mutex_lock_full$FUNC, false
    );
    static final FunctionDescriptor g_static_rec_mutex_unlock_full$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_static_rec_mutex_unlock_full$MH = RuntimeHelper.downcallHandle(
        "g_static_rec_mutex_unlock_full",
        constants$370.g_static_rec_mutex_unlock_full$FUNC, false
    );
}


