// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface GFileMeasureProgressCallback {

    void apply(int x0, long x1, long x2, long x3, jdk.incubator.foreign.MemoryAddress x4);
    static NativeSymbol allocate(GFileMeasureProgressCallback fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(GFileMeasureProgressCallback.class, fi, constants$512.GFileMeasureProgressCallback$FUNC, "(IJJJLjdk/incubator/foreign/MemoryAddress;)V", scope);
    }
    static GFileMeasureProgressCallback ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("GFileMeasureProgressCallback::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (int x0, long x1, long x2, long x3, jdk.incubator.foreign.MemoryAddress x4) -> {
            try {
                constants$513.GFileMeasureProgressCallback$MH.invokeExact(symbol, x0, x1, x2, x3, (jdk.incubator.foreign.Addressable)x4);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


