// Generated by jextract

package gbus;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface GFileProgressCallback {

    void apply(long x0, long x1, jdk.incubator.foreign.MemoryAddress x2);
    static NativeSymbol allocate(GFileProgressCallback fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(GFileProgressCallback.class, fi, constants$512.GFileProgressCallback$FUNC, "(JJLjdk/incubator/foreign/MemoryAddress;)V", scope);
    }
    static GFileProgressCallback ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("GFileProgressCallback::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (long x0, long x1, jdk.incubator.foreign.MemoryAddress x2) -> {
            try {
                constants$512.GFileProgressCallback$MH.invokeExact(symbol, x0, x1, (jdk.incubator.foreign.Addressable)x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


