// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class _GRemoteActionGroupInterface {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            Constants$root.C_LONG_LONG$LAYOUT.withName("g_type"),
            Constants$root.C_LONG_LONG$LAYOUT.withName("g_instance_type")
        ).withName("g_iface"),
        Constants$root.C_POINTER$LAYOUT.withName("activate_action_full"),
        Constants$root.C_POINTER$LAYOUT.withName("change_action_state_full")
    ).withName("_GRemoteActionGroupInterface");
    public static MemoryLayout $LAYOUT() {
        return _GRemoteActionGroupInterface.$struct$LAYOUT;
    }
    public static MemorySegment g_iface$slice(MemorySegment seg) {
        return seg.asSlice(0, 16);
    }
    static final FunctionDescriptor activate_action_full$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle activate_action_full$MH = RuntimeHelper.downcallHandle(
        _GRemoteActionGroupInterface.activate_action_full$FUNC, false
    );
    public interface activate_action_full {

        void apply(MemoryAddress _x0, MemoryAddress _x1, MemoryAddress _x2, MemoryAddress _x3);
        static NativeSymbol allocate(activate_action_full fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(activate_action_full.class, fi, _GRemoteActionGroupInterface.activate_action_full$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V", scope);
        }
        static activate_action_full ofAddress(MemoryAddress addr, ResourceScope scope) {
            NativeSymbol symbol = NativeSymbol.ofAddress("activate_action_full::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (MemoryAddress __x0, MemoryAddress __x1, MemoryAddress __x2, MemoryAddress __x3) -> {
                try {
                    _GRemoteActionGroupInterface.activate_action_full$MH.invokeExact(symbol, (Addressable)__x0, (Addressable)__x1, (Addressable)__x2, (Addressable)__x3);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle activate_action_full$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("activate_action_full"));
    public static VarHandle activate_action_full$VH() {
        return _GRemoteActionGroupInterface.activate_action_full$VH;
    }
    public static MemoryAddress activate_action_full$get(MemorySegment seg) {
        return (MemoryAddress)_GRemoteActionGroupInterface.activate_action_full$VH.get(seg);
    }
    public static void activate_action_full$set( MemorySegment seg, MemoryAddress x) {
        _GRemoteActionGroupInterface.activate_action_full$VH.set(seg, x);
    }
    public static MemoryAddress activate_action_full$get(MemorySegment seg, long index) {
        return (MemoryAddress)_GRemoteActionGroupInterface.activate_action_full$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void activate_action_full$set(MemorySegment seg, long index, MemoryAddress x) {
        _GRemoteActionGroupInterface.activate_action_full$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static activate_action_full activate_action_full (MemorySegment segment, ResourceScope scope) {
        return activate_action_full.ofAddress(activate_action_full$get(segment), scope);
    }
    static final FunctionDescriptor change_action_state_full$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle change_action_state_full$MH = RuntimeHelper.downcallHandle(
        _GRemoteActionGroupInterface.change_action_state_full$FUNC, false
    );
    public interface change_action_state_full {

        void apply(MemoryAddress _x0, MemoryAddress _x1, MemoryAddress _x2, MemoryAddress _x3);
        static NativeSymbol allocate(change_action_state_full fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(change_action_state_full.class, fi, _GRemoteActionGroupInterface.change_action_state_full$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V", scope);
        }
        static change_action_state_full ofAddress(MemoryAddress addr, ResourceScope scope) {
            NativeSymbol symbol = NativeSymbol.ofAddress("change_action_state_full::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (MemoryAddress __x0, MemoryAddress __x1, MemoryAddress __x2, MemoryAddress __x3) -> {
                try {
                    _GRemoteActionGroupInterface.change_action_state_full$MH.invokeExact(symbol, (Addressable)__x0, (Addressable)__x1, (Addressable)__x2, (Addressable)__x3);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle change_action_state_full$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("change_action_state_full"));
    public static VarHandle change_action_state_full$VH() {
        return _GRemoteActionGroupInterface.change_action_state_full$VH;
    }
    public static MemoryAddress change_action_state_full$get(MemorySegment seg) {
        return (MemoryAddress)_GRemoteActionGroupInterface.change_action_state_full$VH.get(seg);
    }
    public static void change_action_state_full$set( MemorySegment seg, MemoryAddress x) {
        _GRemoteActionGroupInterface.change_action_state_full$VH.set(seg, x);
    }
    public static MemoryAddress change_action_state_full$get(MemorySegment seg, long index) {
        return (MemoryAddress)_GRemoteActionGroupInterface.change_action_state_full$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void change_action_state_full$set(MemorySegment seg, long index, MemoryAddress x) {
        _GRemoteActionGroupInterface.change_action_state_full$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static change_action_state_full change_action_state_full (MemorySegment segment, ResourceScope scope) {
        return change_action_state_full.ofAddress(change_action_state_full$get(segment), scope);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


