// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class _GTypeFundamentalInfo {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("type_flags")
    ).withName("_GTypeFundamentalInfo");
    public static MemoryLayout $LAYOUT() {
        return _GTypeFundamentalInfo.$struct$LAYOUT;
    }
    static final VarHandle type_flags$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("type_flags"));
    public static VarHandle type_flags$VH() {
        return _GTypeFundamentalInfo.type_flags$VH;
    }
    public static int type_flags$get(MemorySegment seg) {
        return (int)_GTypeFundamentalInfo.type_flags$VH.get(seg);
    }
    public static void type_flags$set( MemorySegment seg, int x) {
        _GTypeFundamentalInfo.type_flags$VH.set(seg, x);
    }
    public static int type_flags$get(MemorySegment seg, long index) {
        return (int)_GTypeFundamentalInfo.type_flags$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void type_flags$set(MemorySegment seg, long index, int x) {
        _GTypeFundamentalInfo.type_flags$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


