// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$694 {

    static final FunctionDescriptor g_dbus_message_type_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_dbus_message_type_get_type$MH = RuntimeHelper.downcallHandle(
        "g_dbus_message_type_get_type",
        constants$694.g_dbus_message_type_get_type$FUNC, false
    );
    static final FunctionDescriptor g_dbus_message_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_dbus_message_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "g_dbus_message_flags_get_type",
        constants$694.g_dbus_message_flags_get_type$FUNC, false
    );
    static final FunctionDescriptor g_dbus_message_header_field_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_dbus_message_header_field_get_type$MH = RuntimeHelper.downcallHandle(
        "g_dbus_message_header_field_get_type",
        constants$694.g_dbus_message_header_field_get_type$FUNC, false
    );
    static final FunctionDescriptor g_dbus_property_info_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_dbus_property_info_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "g_dbus_property_info_flags_get_type",
        constants$694.g_dbus_property_info_flags_get_type$FUNC, false
    );
    static final FunctionDescriptor g_dbus_subtree_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_dbus_subtree_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "g_dbus_subtree_flags_get_type",
        constants$694.g_dbus_subtree_flags_get_type$FUNC, false
    );
    static final FunctionDescriptor g_dbus_server_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_dbus_server_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "g_dbus_server_flags_get_type",
        constants$694.g_dbus_server_flags_get_type$FUNC, false
    );
}


