// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$918 {

    static final FunctionDescriptor glib_listautoptr_cleanup_GSeekable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GSeekable$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GSeekable",
        constants$918.glib_listautoptr_cleanup_GSeekable$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GSeekable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GSeekable$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GSeekable",
        constants$918.glib_slistautoptr_cleanup_GSeekable$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GSeekable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GSeekable$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GSeekable",
        constants$918.glib_queueautoptr_cleanup_GSeekable$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GSettingsBackend$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GSettingsBackend$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GSettingsBackend",
        constants$918.glib_autoptr_clear_GSettingsBackend$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GSettingsBackend$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GSettingsBackend$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GSettingsBackend",
        constants$918.glib_autoptr_cleanup_GSettingsBackend$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GSettingsBackend$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GSettingsBackend$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GSettingsBackend",
        constants$918.glib_listautoptr_cleanup_GSettingsBackend$FUNC, false
    );
}


