// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$761 {

    static final FunctionDescriptor g_settings_schema_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_settings_schema_get_type$MH = RuntimeHelper.downcallHandle(
        "g_settings_schema_get_type",
        constants$761.g_settings_schema_get_type$FUNC, false
    );
    static final FunctionDescriptor g_settings_schema_ref$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_settings_schema_ref$MH = RuntimeHelper.downcallHandle(
        "g_settings_schema_ref",
        constants$761.g_settings_schema_ref$FUNC, false
    );
    static final FunctionDescriptor g_settings_schema_unref$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_settings_schema_unref$MH = RuntimeHelper.downcallHandle(
        "g_settings_schema_unref",
        constants$761.g_settings_schema_unref$FUNC, false
    );
    static final FunctionDescriptor g_settings_schema_get_id$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_settings_schema_get_id$MH = RuntimeHelper.downcallHandle(
        "g_settings_schema_get_id",
        constants$761.g_settings_schema_get_id$FUNC, false
    );
    static final FunctionDescriptor g_settings_schema_get_path$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_settings_schema_get_path$MH = RuntimeHelper.downcallHandle(
        "g_settings_schema_get_path",
        constants$761.g_settings_schema_get_path$FUNC, false
    );
    static final FunctionDescriptor g_settings_schema_get_key$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_settings_schema_get_key$MH = RuntimeHelper.downcallHandle(
        "g_settings_schema_get_key",
        constants$761.g_settings_schema_get_key$FUNC, false
    );
}


