// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$200 {

    static final FunctionDescriptor g_key_file_set_uint64$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle g_key_file_set_uint64$MH = RuntimeHelper.downcallHandle(
        "g_key_file_set_uint64",
        constants$200.g_key_file_set_uint64$FUNC, false
    );
    static final FunctionDescriptor g_key_file_get_double$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_key_file_get_double$MH = RuntimeHelper.downcallHandle(
        "g_key_file_get_double",
        constants$200.g_key_file_get_double$FUNC, false
    );
    static final FunctionDescriptor g_key_file_set_double$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle g_key_file_set_double$MH = RuntimeHelper.downcallHandle(
        "g_key_file_set_double",
        constants$200.g_key_file_set_double$FUNC, false
    );
    static final FunctionDescriptor g_key_file_get_string_list$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_key_file_get_string_list$MH = RuntimeHelper.downcallHandle(
        "g_key_file_get_string_list",
        constants$200.g_key_file_get_string_list$FUNC, false
    );
    static final FunctionDescriptor g_key_file_set_string_list$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle g_key_file_set_string_list$MH = RuntimeHelper.downcallHandle(
        "g_key_file_set_string_list",
        constants$200.g_key_file_set_string_list$FUNC, false
    );
    static final FunctionDescriptor g_key_file_get_locale_string_list$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_key_file_get_locale_string_list$MH = RuntimeHelper.downcallHandle(
        "g_key_file_get_locale_string_list",
        constants$200.g_key_file_get_locale_string_list$FUNC, false
    );
}


