// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$61 {

    static final FunctionDescriptor g_async_queue_timeout_pop$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle g_async_queue_timeout_pop$MH = RuntimeHelper.downcallHandle(
        "g_async_queue_timeout_pop",
        constants$61.g_async_queue_timeout_pop$FUNC, false
    );
    static final FunctionDescriptor g_async_queue_timeout_pop_unlocked$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle g_async_queue_timeout_pop_unlocked$MH = RuntimeHelper.downcallHandle(
        "g_async_queue_timeout_pop_unlocked",
        constants$61.g_async_queue_timeout_pop_unlocked$FUNC, false
    );
    static final FunctionDescriptor g_async_queue_length$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_async_queue_length$MH = RuntimeHelper.downcallHandle(
        "g_async_queue_length",
        constants$61.g_async_queue_length$FUNC, false
    );
    static final FunctionDescriptor g_async_queue_length_unlocked$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_async_queue_length_unlocked$MH = RuntimeHelper.downcallHandle(
        "g_async_queue_length_unlocked",
        constants$61.g_async_queue_length_unlocked$FUNC, false
    );
    static final FunctionDescriptor g_async_queue_sort$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_async_queue_sort$MH = RuntimeHelper.downcallHandle(
        "g_async_queue_sort",
        constants$61.g_async_queue_sort$FUNC, false
    );
    static final FunctionDescriptor g_async_queue_sort_unlocked$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_async_queue_sort_unlocked$MH = RuntimeHelper.downcallHandle(
        "g_async_queue_sort_unlocked",
        constants$61.g_async_queue_sort_unlocked$FUNC, false
    );
}


