// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1032 {

    static final MemorySegment G_FILE_ATTRIBUTE_UNIX_BLOCKS$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("unix::blocks");
    static final MemorySegment G_FILE_ATTRIBUTE_UNIX_IS_MOUNTPOINT$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("unix::is-mountpoint");
    static final MemorySegment G_FILE_ATTRIBUTE_DOS_IS_ARCHIVE$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("dos::is-archive");
    static final MemorySegment G_FILE_ATTRIBUTE_DOS_IS_SYSTEM$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("dos::is-system");
    static final MemorySegment G_FILE_ATTRIBUTE_DOS_IS_MOUNTPOINT$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("dos::is-mountpoint");
    static final MemorySegment G_FILE_ATTRIBUTE_DOS_REPARSE_POINT_TAG$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("dos::reparse-point-tag");
}


