// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$922 {

    static final FunctionDescriptor glib_autoptr_cleanup_GSettings$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GSettings$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GSettings",
        constants$922.glib_autoptr_cleanup_GSettings$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GSettings$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GSettings$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GSettings",
        constants$922.glib_listautoptr_cleanup_GSettings$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GSettings$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GSettings$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GSettings",
        constants$922.glib_slistautoptr_cleanup_GSettings$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GSettings$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GSettings$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GSettings",
        constants$922.glib_queueautoptr_cleanup_GSettings$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GSimpleActionGroup$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GSimpleActionGroup$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GSimpleActionGroup",
        constants$922.glib_autoptr_clear_GSimpleActionGroup$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GSimpleActionGroup$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GSimpleActionGroup$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GSimpleActionGroup",
        constants$922.glib_autoptr_cleanup_GSimpleActionGroup$FUNC, false
    );
}


