// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$520 {

    static final FunctionDescriptor g_async_initable_new_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_async_initable_new_async$MH = RuntimeHelper.downcallHandle(
        "g_async_initable_new_async",
        constants$520.g_async_initable_new_async$FUNC, true
    );
    static final FunctionDescriptor g_async_initable_newv_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_async_initable_newv_async$MH = RuntimeHelper.downcallHandle(
        "g_async_initable_newv_async",
        constants$520.g_async_initable_newv_async$FUNC, false
    );
    static final FunctionDescriptor g_async_initable_new_valist_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_async_initable_new_valist_async$MH = RuntimeHelper.downcallHandle(
        "g_async_initable_new_valist_async",
        constants$520.g_async_initable_new_valist_async$FUNC, false
    );
    static final FunctionDescriptor g_async_initable_new_finish$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_async_initable_new_finish$MH = RuntimeHelper.downcallHandle(
        "g_async_initable_new_finish",
        constants$520.g_async_initable_new_finish$FUNC, false
    );
    static final FunctionDescriptor g_async_result_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_async_result_get_type$MH = RuntimeHelper.downcallHandle(
        "g_async_result_get_type",
        constants$520.g_async_result_get_type$FUNC, false
    );
    static final FunctionDescriptor g_async_result_get_user_data$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_async_result_get_user_data$MH = RuntimeHelper.downcallHandle(
        "g_async_result_get_user_data",
        constants$520.g_async_result_get_user_data$FUNC, false
    );
}


