// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$726 {

    static final FunctionDescriptor g_menu_item_set_icon$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_menu_item_set_icon$MH = RuntimeHelper.downcallHandle(
        "g_menu_item_set_icon",
        constants$726.g_menu_item_set_icon$FUNC, false
    );
    static final FunctionDescriptor g_dbus_connection_export_menu_model$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_connection_export_menu_model$MH = RuntimeHelper.downcallHandle(
        "g_dbus_connection_export_menu_model",
        constants$726.g_dbus_connection_export_menu_model$FUNC, false
    );
    static final FunctionDescriptor g_dbus_connection_unexport_menu_model$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_dbus_connection_unexport_menu_model$MH = RuntimeHelper.downcallHandle(
        "g_dbus_connection_unexport_menu_model",
        constants$726.g_dbus_connection_unexport_menu_model$FUNC, false
    );
    static final FunctionDescriptor g_mount_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_mount_get_type$MH = RuntimeHelper.downcallHandle(
        "g_mount_get_type",
        constants$726.g_mount_get_type$FUNC, false
    );
    static final FunctionDescriptor g_mount_get_root$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_mount_get_root$MH = RuntimeHelper.downcallHandle(
        "g_mount_get_root",
        constants$726.g_mount_get_root$FUNC, false
    );
    static final FunctionDescriptor g_mount_get_default_location$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_mount_get_default_location$MH = RuntimeHelper.downcallHandle(
        "g_mount_get_default_location",
        constants$726.g_mount_get_default_location$FUNC, false
    );
}


