// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$927 {

    static final FunctionDescriptor glib_autoptr_cleanup_GSocketAddressEnumerator$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GSocketAddressEnumerator$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GSocketAddressEnumerator",
        constants$927.glib_autoptr_cleanup_GSocketAddressEnumerator$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GSocketAddressEnumerator$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GSocketAddressEnumerator$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GSocketAddressEnumerator",
        constants$927.glib_listautoptr_cleanup_GSocketAddressEnumerator$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GSocketAddressEnumerator$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GSocketAddressEnumerator$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GSocketAddressEnumerator",
        constants$927.glib_slistautoptr_cleanup_GSocketAddressEnumerator$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GSocketAddressEnumerator$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GSocketAddressEnumerator$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GSocketAddressEnumerator",
        constants$927.glib_queueautoptr_cleanup_GSocketAddressEnumerator$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GSocketAddress$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GSocketAddress$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GSocketAddress",
        constants$927.glib_autoptr_clear_GSocketAddress$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GSocketAddress$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GSocketAddress$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GSocketAddress",
        constants$927.glib_autoptr_cleanup_GSocketAddress$FUNC, false
    );
}


