// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$691 {

    static final FunctionDescriptor g_resolver_record_type_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_resolver_record_type_get_type$MH = RuntimeHelper.downcallHandle(
        "g_resolver_record_type_get_type",
        constants$691.g_resolver_record_type_get_type$FUNC, false
    );
    static final FunctionDescriptor g_resource_error_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_resource_error_get_type$MH = RuntimeHelper.downcallHandle(
        "g_resource_error_get_type",
        constants$691.g_resource_error_get_type$FUNC, false
    );
    static final FunctionDescriptor g_resource_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_resource_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "g_resource_flags_get_type",
        constants$691.g_resource_flags_get_type$FUNC, false
    );
    static final FunctionDescriptor g_resource_lookup_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_resource_lookup_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "g_resource_lookup_flags_get_type",
        constants$691.g_resource_lookup_flags_get_type$FUNC, false
    );
    static final FunctionDescriptor g_socket_family_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_socket_family_get_type$MH = RuntimeHelper.downcallHandle(
        "g_socket_family_get_type",
        constants$691.g_socket_family_get_type$FUNC, false
    );
    static final FunctionDescriptor g_socket_type_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_socket_type_get_type$MH = RuntimeHelper.downcallHandle(
        "g_socket_type_get_type",
        constants$691.g_socket_type_get_type$FUNC, false
    );
}


