// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$274 {

    static final FunctionDescriptor g_sequence_move$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_sequence_move$MH = RuntimeHelper.downcallHandle(
        "g_sequence_move",
        constants$274.g_sequence_move$FUNC, false
    );
    static final FunctionDescriptor g_sequence_swap$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_sequence_swap$MH = RuntimeHelper.downcallHandle(
        "g_sequence_swap",
        constants$274.g_sequence_swap$FUNC, false
    );
    static final FunctionDescriptor g_sequence_insert_sorted$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_sequence_insert_sorted$MH = RuntimeHelper.downcallHandle(
        "g_sequence_insert_sorted",
        constants$274.g_sequence_insert_sorted$FUNC, false
    );
    static final FunctionDescriptor g_sequence_insert_sorted_iter$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_sequence_insert_sorted_iter$MH = RuntimeHelper.downcallHandle(
        "g_sequence_insert_sorted_iter",
        constants$274.g_sequence_insert_sorted_iter$FUNC, false
    );
    static final FunctionDescriptor g_sequence_sort_changed$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_sequence_sort_changed$MH = RuntimeHelper.downcallHandle(
        "g_sequence_sort_changed",
        constants$274.g_sequence_sort_changed$FUNC, false
    );
    static final FunctionDescriptor g_sequence_sort_changed_iter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_sequence_sort_changed_iter$MH = RuntimeHelper.downcallHandle(
        "g_sequence_sort_changed_iter",
        constants$274.g_sequence_sort_changed_iter$FUNC, false
    );
}


