// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$287 {

    static final FunctionDescriptor g_strcasecmp$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_strcasecmp$MH = RuntimeHelper.downcallHandle(
        "g_strcasecmp",
        constants$287.g_strcasecmp$FUNC, false
    );
    static final FunctionDescriptor g_strncasecmp$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_strncasecmp$MH = RuntimeHelper.downcallHandle(
        "g_strncasecmp",
        constants$287.g_strncasecmp$FUNC, false
    );
    static final FunctionDescriptor g_strdown$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_strdown$MH = RuntimeHelper.downcallHandle(
        "g_strdown",
        constants$287.g_strdown$FUNC, false
    );
    static final FunctionDescriptor g_strup$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_strup$MH = RuntimeHelper.downcallHandle(
        "g_strup",
        constants$287.g_strup$FUNC, false
    );
    static final FunctionDescriptor g_strdup$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_strdup$MH = RuntimeHelper.downcallHandle(
        "g_strdup",
        constants$287.g_strdup$FUNC, false
    );
    static final FunctionDescriptor g_strdup_printf$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_strdup_printf$MH = RuntimeHelper.downcallHandle(
        "g_strdup_printf",
        constants$287.g_strdup_printf$FUNC, true
    );
}


