// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$230 {

    static final FunctionDescriptor g_variant_new_parsed_va$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_new_parsed_va$MH = RuntimeHelper.downcallHandle(
        "g_variant_new_parsed_va",
        constants$230.g_variant_new_parsed_va$FUNC, false
    );
    static final FunctionDescriptor g_variant_parse_error_print_context$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_parse_error_print_context$MH = RuntimeHelper.downcallHandle(
        "g_variant_parse_error_print_context",
        constants$230.g_variant_parse_error_print_context$FUNC, false
    );
    static final FunctionDescriptor g_variant_compare$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_compare$MH = RuntimeHelper.downcallHandle(
        "g_variant_compare",
        constants$230.g_variant_compare$FUNC, false
    );
    static final FunctionDescriptor g_variant_dict_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_dict_new$MH = RuntimeHelper.downcallHandle(
        "g_variant_dict_new",
        constants$230.g_variant_dict_new$FUNC, false
    );
    static final FunctionDescriptor g_variant_dict_init$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_dict_init$MH = RuntimeHelper.downcallHandle(
        "g_variant_dict_init",
        constants$230.g_variant_dict_init$FUNC, false
    );
    static final FunctionDescriptor g_variant_dict_lookup$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_dict_lookup$MH = RuntimeHelper.downcallHandle(
        "g_variant_dict_lookup",
        constants$230.g_variant_dict_lookup$FUNC, true
    );
}


