// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$820 {

    static final FunctionDescriptor g_test_dbus_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_test_dbus_new$MH = RuntimeHelper.downcallHandle(
        "g_test_dbus_new",
        constants$820.g_test_dbus_new$FUNC, false
    );
    static final FunctionDescriptor g_test_dbus_get_flags$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_test_dbus_get_flags$MH = RuntimeHelper.downcallHandle(
        "g_test_dbus_get_flags",
        constants$820.g_test_dbus_get_flags$FUNC, false
    );
    static final FunctionDescriptor g_test_dbus_get_bus_address$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_test_dbus_get_bus_address$MH = RuntimeHelper.downcallHandle(
        "g_test_dbus_get_bus_address",
        constants$820.g_test_dbus_get_bus_address$FUNC, false
    );
    static final FunctionDescriptor g_test_dbus_add_service_dir$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_test_dbus_add_service_dir$MH = RuntimeHelper.downcallHandle(
        "g_test_dbus_add_service_dir",
        constants$820.g_test_dbus_add_service_dir$FUNC, false
    );
    static final FunctionDescriptor g_test_dbus_up$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_test_dbus_up$MH = RuntimeHelper.downcallHandle(
        "g_test_dbus_up",
        constants$820.g_test_dbus_up$FUNC, false
    );
    static final FunctionDescriptor g_test_dbus_stop$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_test_dbus_stop$MH = RuntimeHelper.downcallHandle(
        "g_test_dbus_stop",
        constants$820.g_test_dbus_stop$FUNC, false
    );
}


