// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$847 {

    static final FunctionDescriptor glib_autoptr_cleanup_GAppLaunchContext$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GAppLaunchContext$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GAppLaunchContext",
        constants$847.glib_autoptr_cleanup_GAppLaunchContext$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GAppLaunchContext$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GAppLaunchContext$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GAppLaunchContext",
        constants$847.glib_listautoptr_cleanup_GAppLaunchContext$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GAppLaunchContext$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GAppLaunchContext$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GAppLaunchContext",
        constants$847.glib_slistautoptr_cleanup_GAppLaunchContext$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GAppLaunchContext$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GAppLaunchContext$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GAppLaunchContext",
        constants$847.glib_queueautoptr_cleanup_GAppLaunchContext$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GAppInfoMonitor$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GAppInfoMonitor$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GAppInfoMonitor",
        constants$847.glib_autoptr_clear_GAppInfoMonitor$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GAppInfoMonitor$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GAppInfoMonitor$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GAppInfoMonitor",
        constants$847.glib_autoptr_cleanup_GAppInfoMonitor$FUNC, false
    );
}


