// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$423 {

    static final FunctionDescriptor g_param_spec_pool_list_owned$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle g_param_spec_pool_list_owned$MH = RuntimeHelper.downcallHandle(
        "g_param_spec_pool_list_owned",
        constants$423.g_param_spec_pool_list_owned$FUNC, false
    );
    static final FunctionDescriptor g_param_spec_pool_list$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_param_spec_pool_list$MH = RuntimeHelper.downcallHandle(
        "g_param_spec_pool_list",
        constants$423.g_param_spec_pool_list$FUNC, false
    );
    static final FunctionDescriptor GCallback$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle GCallback$MH = RuntimeHelper.downcallHandle(
        constants$423.GCallback$FUNC, false
    );
    static final FunctionDescriptor GClosureNotify$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GClosureNotify$MH = RuntimeHelper.downcallHandle(
        constants$423.GClosureNotify$FUNC, false
    );
}


