// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$617 {

    static final FunctionDescriptor g_dbus_proxy_get_cached_property$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_proxy_get_cached_property$MH = RuntimeHelper.downcallHandle(
        "g_dbus_proxy_get_cached_property",
        constants$617.g_dbus_proxy_get_cached_property$FUNC, false
    );
    static final FunctionDescriptor g_dbus_proxy_set_cached_property$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_proxy_set_cached_property$MH = RuntimeHelper.downcallHandle(
        "g_dbus_proxy_set_cached_property",
        constants$617.g_dbus_proxy_set_cached_property$FUNC, false
    );
    static final FunctionDescriptor g_dbus_proxy_get_cached_property_names$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_proxy_get_cached_property_names$MH = RuntimeHelper.downcallHandle(
        "g_dbus_proxy_get_cached_property_names",
        constants$617.g_dbus_proxy_get_cached_property_names$FUNC, false
    );
    static final FunctionDescriptor g_dbus_proxy_call$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_proxy_call$MH = RuntimeHelper.downcallHandle(
        "g_dbus_proxy_call",
        constants$617.g_dbus_proxy_call$FUNC, false
    );
    static final FunctionDescriptor g_dbus_proxy_call_finish$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_proxy_call_finish$MH = RuntimeHelper.downcallHandle(
        "g_dbus_proxy_call_finish",
        constants$617.g_dbus_proxy_call_finish$FUNC, false
    );
    static final FunctionDescriptor g_dbus_proxy_call_sync$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_proxy_call_sync$MH = RuntimeHelper.downcallHandle(
        "g_dbus_proxy_call_sync",
        constants$617.g_dbus_proxy_call_sync$FUNC, false
    );
}


