// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$114 {

    static final FunctionDescriptor g_file_read_link$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_read_link$MH = RuntimeHelper.downcallHandle(
        "g_file_read_link",
        constants$114.g_file_read_link$FUNC, false
    );
    static final FunctionDescriptor g_mkdtemp$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_mkdtemp$MH = RuntimeHelper.downcallHandle(
        "g_mkdtemp",
        constants$114.g_mkdtemp$FUNC, false
    );
    static final FunctionDescriptor g_mkdtemp_full$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_mkdtemp_full$MH = RuntimeHelper.downcallHandle(
        "g_mkdtemp_full",
        constants$114.g_mkdtemp_full$FUNC, false
    );
    static final FunctionDescriptor g_mkstemp$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_mkstemp$MH = RuntimeHelper.downcallHandle(
        "g_mkstemp",
        constants$114.g_mkstemp$FUNC, false
    );
    static final FunctionDescriptor g_mkstemp_full$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_mkstemp_full$MH = RuntimeHelper.downcallHandle(
        "g_mkstemp_full",
        constants$114.g_mkstemp_full$FUNC, false
    );
    static final FunctionDescriptor g_file_open_tmp$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_open_tmp$MH = RuntimeHelper.downcallHandle(
        "g_file_open_tmp",
        constants$114.g_file_open_tmp$FUNC, false
    );
}


