// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$984 {

    static final FunctionDescriptor glib_autoptr_cleanup_GattService1Skeleton$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GattService1Skeleton$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GattService1Skeleton",
        constants$984.glib_autoptr_cleanup_GattService1Skeleton$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GattService1Skeleton$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GattService1Skeleton$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GattService1Skeleton",
        constants$984.glib_listautoptr_cleanup_GattService1Skeleton$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GattService1Skeleton$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GattService1Skeleton$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GattService1Skeleton",
        constants$984.glib_slistautoptr_cleanup_GattService1Skeleton$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GattService1Skeleton$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GattService1Skeleton$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GattService1Skeleton",
        constants$984.glib_queueautoptr_cleanup_GattService1Skeleton$FUNC, false
    );
    static final FunctionDescriptor gatt_service1_skeleton_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gatt_service1_skeleton_new$MH = RuntimeHelper.downcallHandle(
        "gatt_service1_skeleton_new",
        constants$984.gatt_service1_skeleton_new$FUNC, false
    );
    static final FunctionDescriptor gatt_characteristic1_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gatt_characteristic1_get_type$MH = RuntimeHelper.downcallHandle(
        "gatt_characteristic1_get_type",
        constants$984.gatt_characteristic1_get_type$FUNC, false
    );
}


