// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$62 {

    static final FunctionDescriptor g_async_queue_remove$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_async_queue_remove$MH = RuntimeHelper.downcallHandle(
        "g_async_queue_remove",
        constants$62.g_async_queue_remove$FUNC, false
    );
    static final FunctionDescriptor g_async_queue_remove_unlocked$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_async_queue_remove_unlocked$MH = RuntimeHelper.downcallHandle(
        "g_async_queue_remove_unlocked",
        constants$62.g_async_queue_remove_unlocked$FUNC, false
    );
    static final FunctionDescriptor g_async_queue_push_front$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_async_queue_push_front$MH = RuntimeHelper.downcallHandle(
        "g_async_queue_push_front",
        constants$62.g_async_queue_push_front$FUNC, false
    );
    static final FunctionDescriptor g_async_queue_push_front_unlocked$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_async_queue_push_front_unlocked$MH = RuntimeHelper.downcallHandle(
        "g_async_queue_push_front_unlocked",
        constants$62.g_async_queue_push_front_unlocked$FUNC, false
    );
    static final FunctionDescriptor g_async_queue_timed_pop$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_async_queue_timed_pop$MH = RuntimeHelper.downcallHandle(
        "g_async_queue_timed_pop",
        constants$62.g_async_queue_timed_pop$FUNC, false
    );
    static final FunctionDescriptor g_async_queue_timed_pop_unlocked$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_async_queue_timed_pop_unlocked$MH = RuntimeHelper.downcallHandle(
        "g_async_queue_timed_pop_unlocked",
        constants$62.g_async_queue_timed_pop_unlocked$FUNC, false
    );
}


