// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$530 {

    static final FunctionDescriptor g_output_stream_writev_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_output_stream_writev_async$MH = RuntimeHelper.downcallHandle(
        "g_output_stream_writev_async",
        constants$530.g_output_stream_writev_async$FUNC, false
    );
    static final FunctionDescriptor g_output_stream_writev_finish$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_output_stream_writev_finish$MH = RuntimeHelper.downcallHandle(
        "g_output_stream_writev_finish",
        constants$530.g_output_stream_writev_finish$FUNC, false
    );
    static final FunctionDescriptor g_output_stream_writev_all_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_output_stream_writev_all_async$MH = RuntimeHelper.downcallHandle(
        "g_output_stream_writev_all_async",
        constants$530.g_output_stream_writev_all_async$FUNC, false
    );
    static final FunctionDescriptor g_output_stream_writev_all_finish$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_output_stream_writev_all_finish$MH = RuntimeHelper.downcallHandle(
        "g_output_stream_writev_all_finish",
        constants$530.g_output_stream_writev_all_finish$FUNC, false
    );
    static final FunctionDescriptor g_output_stream_write_bytes_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_output_stream_write_bytes_async$MH = RuntimeHelper.downcallHandle(
        "g_output_stream_write_bytes_async",
        constants$530.g_output_stream_write_bytes_async$FUNC, false
    );
    static final FunctionDescriptor g_output_stream_write_bytes_finish$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_output_stream_write_bytes_finish$MH = RuntimeHelper.downcallHandle(
        "g_output_stream_write_bytes_finish",
        constants$530.g_output_stream_write_bytes_finish$FUNC, false
    );
}


