// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$863 {

    static final FunctionDescriptor glib_listautoptr_cleanup_GDBusAuthObserver$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GDBusAuthObserver$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GDBusAuthObserver",
        constants$863.glib_listautoptr_cleanup_GDBusAuthObserver$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GDBusAuthObserver$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GDBusAuthObserver$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GDBusAuthObserver",
        constants$863.glib_slistautoptr_cleanup_GDBusAuthObserver$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GDBusAuthObserver$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GDBusAuthObserver$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GDBusAuthObserver",
        constants$863.glib_queueautoptr_cleanup_GDBusAuthObserver$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GDBusConnection$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GDBusConnection$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GDBusConnection",
        constants$863.glib_autoptr_clear_GDBusConnection$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GDBusConnection$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GDBusConnection$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GDBusConnection",
        constants$863.glib_autoptr_cleanup_GDBusConnection$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GDBusConnection$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GDBusConnection$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GDBusConnection",
        constants$863.glib_listautoptr_cleanup_GDBusConnection$FUNC, false
    );
}


