// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$616 {

    static final FunctionDescriptor g_dbus_proxy_get_object_path$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_proxy_get_object_path$MH = RuntimeHelper.downcallHandle(
        "g_dbus_proxy_get_object_path",
        constants$616.g_dbus_proxy_get_object_path$FUNC, false
    );
    static final FunctionDescriptor g_dbus_proxy_get_interface_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_proxy_get_interface_name$MH = RuntimeHelper.downcallHandle(
        "g_dbus_proxy_get_interface_name",
        constants$616.g_dbus_proxy_get_interface_name$FUNC, false
    );
    static final FunctionDescriptor g_dbus_proxy_get_default_timeout$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_proxy_get_default_timeout$MH = RuntimeHelper.downcallHandle(
        "g_dbus_proxy_get_default_timeout",
        constants$616.g_dbus_proxy_get_default_timeout$FUNC, false
    );
    static final FunctionDescriptor g_dbus_proxy_set_default_timeout$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_dbus_proxy_set_default_timeout$MH = RuntimeHelper.downcallHandle(
        "g_dbus_proxy_set_default_timeout",
        constants$616.g_dbus_proxy_set_default_timeout$FUNC, false
    );
    static final FunctionDescriptor g_dbus_proxy_get_interface_info$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_proxy_get_interface_info$MH = RuntimeHelper.downcallHandle(
        "g_dbus_proxy_get_interface_info",
        constants$616.g_dbus_proxy_get_interface_info$FUNC, false
    );
    static final FunctionDescriptor g_dbus_proxy_set_interface_info$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_proxy_set_interface_info$MH = RuntimeHelper.downcallHandle(
        "g_dbus_proxy_set_interface_info",
        constants$616.g_dbus_proxy_set_interface_info$FUNC, false
    );
}


