// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$639 {

    static final FunctionDescriptor g_file_read$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_read$MH = RuntimeHelper.downcallHandle(
        "g_file_read",
        constants$639.g_file_read$FUNC, false
    );
    static final FunctionDescriptor g_file_read_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_read_async$MH = RuntimeHelper.downcallHandle(
        "g_file_read_async",
        constants$639.g_file_read_async$FUNC, false
    );
    static final FunctionDescriptor g_file_read_finish$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_read_finish$MH = RuntimeHelper.downcallHandle(
        "g_file_read_finish",
        constants$639.g_file_read_finish$FUNC, false
    );
    static final FunctionDescriptor g_file_append_to$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_append_to$MH = RuntimeHelper.downcallHandle(
        "g_file_append_to",
        constants$639.g_file_append_to$FUNC, false
    );
    static final FunctionDescriptor g_file_create$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_create$MH = RuntimeHelper.downcallHandle(
        "g_file_create",
        constants$639.g_file_create$FUNC, false
    );
    static final FunctionDescriptor g_file_replace$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_replace$MH = RuntimeHelper.downcallHandle(
        "g_file_replace",
        constants$639.g_file_replace$FUNC, false
    );
}


