// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$189 {

    static final FunctionDescriptor g_io_channel_seek$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_io_channel_seek$MH = RuntimeHelper.downcallHandle(
        "g_io_channel_seek",
        constants$189.g_io_channel_seek$FUNC, false
    );
    static final FunctionDescriptor g_io_channel_close$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_io_channel_close$MH = RuntimeHelper.downcallHandle(
        "g_io_channel_close",
        constants$189.g_io_channel_close$FUNC, false
    );
    static final FunctionDescriptor g_io_channel_shutdown$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_io_channel_shutdown$MH = RuntimeHelper.downcallHandle(
        "g_io_channel_shutdown",
        constants$189.g_io_channel_shutdown$FUNC, false
    );
    static final FunctionDescriptor g_io_add_watch_full$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_io_add_watch_full$MH = RuntimeHelper.downcallHandle(
        "g_io_add_watch_full",
        constants$189.g_io_add_watch_full$FUNC, false
    );
    static final FunctionDescriptor g_io_create_watch$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_io_create_watch$MH = RuntimeHelper.downcallHandle(
        "g_io_create_watch",
        constants$189.g_io_create_watch$FUNC, false
    );
    static final FunctionDescriptor g_io_add_watch$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_io_add_watch$MH = RuntimeHelper.downcallHandle(
        "g_io_add_watch",
        constants$189.g_io_add_watch$FUNC, false
    );
}


