// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$828 {

    static final FunctionDescriptor g_tls_connection_set_require_close_notify$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_tls_connection_set_require_close_notify$MH = RuntimeHelper.downcallHandle(
        "g_tls_connection_set_require_close_notify",
        constants$828.g_tls_connection_set_require_close_notify$FUNC, false
    );
    static final FunctionDescriptor g_tls_connection_get_require_close_notify$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_tls_connection_get_require_close_notify$MH = RuntimeHelper.downcallHandle(
        "g_tls_connection_get_require_close_notify",
        constants$828.g_tls_connection_get_require_close_notify$FUNC, false
    );
    static final FunctionDescriptor g_tls_connection_set_rehandshake_mode$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_tls_connection_set_rehandshake_mode$MH = RuntimeHelper.downcallHandle(
        "g_tls_connection_set_rehandshake_mode",
        constants$828.g_tls_connection_set_rehandshake_mode$FUNC, false
    );
    static final FunctionDescriptor g_tls_connection_get_rehandshake_mode$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_tls_connection_get_rehandshake_mode$MH = RuntimeHelper.downcallHandle(
        "g_tls_connection_get_rehandshake_mode",
        constants$828.g_tls_connection_get_rehandshake_mode$FUNC, false
    );
    static final FunctionDescriptor g_tls_connection_set_advertised_protocols$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_tls_connection_set_advertised_protocols$MH = RuntimeHelper.downcallHandle(
        "g_tls_connection_set_advertised_protocols",
        constants$828.g_tls_connection_set_advertised_protocols$FUNC, false
    );
    static final FunctionDescriptor g_tls_connection_get_negotiated_protocol$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_tls_connection_get_negotiated_protocol$MH = RuntimeHelper.downcallHandle(
        "g_tls_connection_get_negotiated_protocol",
        constants$828.g_tls_connection_get_negotiated_protocol$FUNC, false
    );
}


