// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$383 {

    static final FunctionDescriptor glib_queueautoptr_cleanup_GRand$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GRand$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GRand",
        constants$383.glib_queueautoptr_cleanup_GRand$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GRegex$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GRegex$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GRegex",
        constants$383.glib_autoptr_clear_GRegex$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GRegex$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GRegex$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GRegex",
        constants$383.glib_autoptr_cleanup_GRegex$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GRegex$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GRegex$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GRegex",
        constants$383.glib_listautoptr_cleanup_GRegex$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GRegex$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GRegex$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GRegex",
        constants$383.glib_slistautoptr_cleanup_GRegex$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GRegex$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GRegex$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GRegex",
        constants$383.glib_queueautoptr_cleanup_GRegex$FUNC, false
    );
}


