// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$666 {

    static final FunctionDescriptor g_file_info_get_deletion_date$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_info_get_deletion_date$MH = RuntimeHelper.downcallHandle(
        "g_file_info_get_deletion_date",
        constants$666.g_file_info_get_deletion_date$FUNC, false
    );
    static final FunctionDescriptor g_file_info_get_file_type$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_info_get_file_type$MH = RuntimeHelper.downcallHandle(
        "g_file_info_get_file_type",
        constants$666.g_file_info_get_file_type$FUNC, false
    );
    static final FunctionDescriptor g_file_info_get_is_hidden$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_info_get_is_hidden$MH = RuntimeHelper.downcallHandle(
        "g_file_info_get_is_hidden",
        constants$666.g_file_info_get_is_hidden$FUNC, false
    );
    static final FunctionDescriptor g_file_info_get_is_backup$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_info_get_is_backup$MH = RuntimeHelper.downcallHandle(
        "g_file_info_get_is_backup",
        constants$666.g_file_info_get_is_backup$FUNC, false
    );
    static final FunctionDescriptor g_file_info_get_is_symlink$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_info_get_is_symlink$MH = RuntimeHelper.downcallHandle(
        "g_file_info_get_is_symlink",
        constants$666.g_file_info_get_is_symlink$FUNC, false
    );
    static final FunctionDescriptor g_file_info_get_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_info_get_name$MH = RuntimeHelper.downcallHandle(
        "g_file_info_get_name",
        constants$666.g_file_info_get_name$FUNC, false
    );
}


