// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$97 {

    static final FunctionDescriptor g_date_get_sunday_weeks_in_year$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle g_date_get_sunday_weeks_in_year$MH = RuntimeHelper.downcallHandle(
        "g_date_get_sunday_weeks_in_year",
        constants$97.g_date_get_sunday_weeks_in_year$FUNC, false
    );
    static final FunctionDescriptor g_date_days_between$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_date_days_between$MH = RuntimeHelper.downcallHandle(
        "g_date_days_between",
        constants$97.g_date_days_between$FUNC, false
    );
    static final FunctionDescriptor g_date_compare$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_date_compare$MH = RuntimeHelper.downcallHandle(
        "g_date_compare",
        constants$97.g_date_compare$FUNC, false
    );
    static final FunctionDescriptor g_date_to_struct_tm$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_date_to_struct_tm$MH = RuntimeHelper.downcallHandle(
        "g_date_to_struct_tm",
        constants$97.g_date_to_struct_tm$FUNC, false
    );
    static final FunctionDescriptor g_date_clamp$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_date_clamp$MH = RuntimeHelper.downcallHandle(
        "g_date_clamp",
        constants$97.g_date_clamp$FUNC, false
    );
    static final FunctionDescriptor g_date_order$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_date_order$MH = RuntimeHelper.downcallHandle(
        "g_date_order",
        constants$97.g_date_order$FUNC, false
    );
}


