// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$369 {

    static final FunctionDescriptor glib_autoptr_cleanup_GKeyFile$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GKeyFile$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GKeyFile",
        constants$369.glib_autoptr_cleanup_GKeyFile$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GKeyFile$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GKeyFile$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GKeyFile",
        constants$369.glib_listautoptr_cleanup_GKeyFile$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GKeyFile$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GKeyFile$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GKeyFile",
        constants$369.glib_slistautoptr_cleanup_GKeyFile$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GKeyFile$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GKeyFile$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GKeyFile",
        constants$369.glib_queueautoptr_cleanup_GKeyFile$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GList$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GList$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GList",
        constants$369.glib_autoptr_clear_GList$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GList$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GList$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GList",
        constants$369.glib_autoptr_cleanup_GList$FUNC, false
    );
}


