// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$479 {

    static final FunctionDescriptor g_value_array_prepend$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_value_array_prepend$MH = RuntimeHelper.downcallHandle(
        "g_value_array_prepend",
        constants$479.g_value_array_prepend$FUNC, false
    );
    static final FunctionDescriptor g_value_array_append$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_value_array_append$MH = RuntimeHelper.downcallHandle(
        "g_value_array_append",
        constants$479.g_value_array_append$FUNC, false
    );
    static final FunctionDescriptor g_value_array_insert$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_value_array_insert$MH = RuntimeHelper.downcallHandle(
        "g_value_array_insert",
        constants$479.g_value_array_insert$FUNC, false
    );
    static final FunctionDescriptor g_value_array_remove$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_value_array_remove$MH = RuntimeHelper.downcallHandle(
        "g_value_array_remove",
        constants$479.g_value_array_remove$FUNC, false
    );
    static final FunctionDescriptor g_value_array_sort$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_value_array_sort$MH = RuntimeHelper.downcallHandle(
        "g_value_array_sort",
        constants$479.g_value_array_sort$FUNC, false
    );
    static final FunctionDescriptor g_value_array_sort_with_data$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_value_array_sort_with_data$MH = RuntimeHelper.downcallHandle(
        "g_value_array_sort_with_data",
        constants$479.g_value_array_sort_with_data$FUNC, false
    );
}


