// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$288 {

    static final FunctionDescriptor g_strdup_vprintf$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_strdup_vprintf$MH = RuntimeHelper.downcallHandle(
        "g_strdup_vprintf",
        constants$288.g_strdup_vprintf$FUNC, false
    );
    static final FunctionDescriptor g_strndup$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle g_strndup$MH = RuntimeHelper.downcallHandle(
        "g_strndup",
        constants$288.g_strndup$FUNC, false
    );
    static final FunctionDescriptor g_strnfill$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_CHAR$LAYOUT
    );
    static final MethodHandle g_strnfill$MH = RuntimeHelper.downcallHandle(
        "g_strnfill",
        constants$288.g_strnfill$FUNC, false
    );
    static final FunctionDescriptor g_strconcat$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_strconcat$MH = RuntimeHelper.downcallHandle(
        "g_strconcat",
        constants$288.g_strconcat$FUNC, true
    );
    static final FunctionDescriptor g_strjoin$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_strjoin$MH = RuntimeHelper.downcallHandle(
        "g_strjoin",
        constants$288.g_strjoin$FUNC, true
    );
    static final FunctionDescriptor g_strcompress$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_strcompress$MH = RuntimeHelper.downcallHandle(
        "g_strcompress",
        constants$288.g_strcompress$FUNC, false
    );
}


