// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$794 {

    static final FunctionDescriptor g_socket_client_get_tls_validation_flags$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_socket_client_get_tls_validation_flags$MH = RuntimeHelper.downcallHandle(
        "g_socket_client_get_tls_validation_flags",
        constants$794.g_socket_client_get_tls_validation_flags$FUNC, false
    );
    static final FunctionDescriptor g_socket_client_set_tls_validation_flags$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_socket_client_set_tls_validation_flags$MH = RuntimeHelper.downcallHandle(
        "g_socket_client_set_tls_validation_flags",
        constants$794.g_socket_client_set_tls_validation_flags$FUNC, false
    );
    static final FunctionDescriptor g_socket_client_get_proxy_resolver$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_socket_client_get_proxy_resolver$MH = RuntimeHelper.downcallHandle(
        "g_socket_client_get_proxy_resolver",
        constants$794.g_socket_client_get_proxy_resolver$FUNC, false
    );
    static final FunctionDescriptor g_socket_client_set_proxy_resolver$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_socket_client_set_proxy_resolver$MH = RuntimeHelper.downcallHandle(
        "g_socket_client_set_proxy_resolver",
        constants$794.g_socket_client_set_proxy_resolver$FUNC, false
    );
    static final FunctionDescriptor g_socket_client_connect$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_socket_client_connect$MH = RuntimeHelper.downcallHandle(
        "g_socket_client_connect",
        constants$794.g_socket_client_connect$FUNC, false
    );
    static final FunctionDescriptor g_socket_client_connect_to_host$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_socket_client_connect_to_host$MH = RuntimeHelper.downcallHandle(
        "g_socket_client_connect_to_host",
        constants$794.g_socket_client_connect_to_host$FUNC, false
    );
}


