// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$723 {

    static final FunctionDescriptor g_menu_append_submenu$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_menu_append_submenu$MH = RuntimeHelper.downcallHandle(
        "g_menu_append_submenu",
        constants$723.g_menu_append_submenu$FUNC, false
    );
    static final FunctionDescriptor g_menu_item_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_menu_item_get_type$MH = RuntimeHelper.downcallHandle(
        "g_menu_item_get_type",
        constants$723.g_menu_item_get_type$FUNC, false
    );
    static final FunctionDescriptor g_menu_item_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_menu_item_new$MH = RuntimeHelper.downcallHandle(
        "g_menu_item_new",
        constants$723.g_menu_item_new$FUNC, false
    );
    static final FunctionDescriptor g_menu_item_new_from_model$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_menu_item_new_from_model$MH = RuntimeHelper.downcallHandle(
        "g_menu_item_new_from_model",
        constants$723.g_menu_item_new_from_model$FUNC, false
    );
    static final FunctionDescriptor g_menu_item_new_submenu$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_menu_item_new_submenu$MH = RuntimeHelper.downcallHandle(
        "g_menu_item_new_submenu",
        constants$723.g_menu_item_new_submenu$FUNC, false
    );
    static final FunctionDescriptor g_menu_item_new_section$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_menu_item_new_section$MH = RuntimeHelper.downcallHandle(
        "g_menu_item_new_section",
        constants$723.g_menu_item_new_section$FUNC, false
    );
}


