// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$581 {

    static final FunctionDescriptor g_dbus_connection_unregister_subtree$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_dbus_connection_unregister_subtree$MH = RuntimeHelper.downcallHandle(
        "g_dbus_connection_unregister_subtree",
        constants$581.g_dbus_connection_unregister_subtree$FUNC, false
    );
    static final FunctionDescriptor GDBusSignalCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GDBusSignalCallback$MH = RuntimeHelper.downcallHandle(
        constants$581.GDBusSignalCallback$FUNC, false
    );
    static final FunctionDescriptor g_dbus_connection_signal_subscribe$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_dbus_connection_signal_subscribe$MH = RuntimeHelper.downcallHandle(
        "g_dbus_connection_signal_subscribe",
        constants$581.g_dbus_connection_signal_subscribe$FUNC, false
    );
    static final FunctionDescriptor g_dbus_connection_signal_unsubscribe$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_dbus_connection_signal_unsubscribe$MH = RuntimeHelper.downcallHandle(
        "g_dbus_connection_signal_unsubscribe",
        constants$581.g_dbus_connection_signal_unsubscribe$FUNC, false
    );
    static final FunctionDescriptor GDBusMessageFilterFunction$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
}


