// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface GCompletionStrncmpFunc {

    int apply(MemoryAddress s1, MemoryAddress s2, long n);
    static NativeSymbol allocate(GCompletionStrncmpFunc fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(GCompletionStrncmpFunc.class, fi, constants$327.GCompletionStrncmpFunc$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;J)I", scope);
    }
    static GCompletionStrncmpFunc ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("GCompletionStrncmpFunc::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (MemoryAddress _s1, MemoryAddress _s2, long _n) -> {
            try {
                return (int)constants$327.GCompletionStrncmpFunc$MH.invokeExact(symbol, (Addressable)_s1, (Addressable)_s2, _n);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


