// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface GDBusMessageFilterFunction {

    Addressable apply(MemoryAddress connection, MemoryAddress message, int incoming, MemoryAddress user_data);
    static NativeSymbol allocate(GDBusMessageFilterFunction fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(GDBusMessageFilterFunction.class, fi, constants$581.GDBusMessageFilterFunction$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/Addressable;", scope);
    }
    static GDBusMessageFilterFunction ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("GDBusMessageFilterFunction::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (MemoryAddress _connection, MemoryAddress _message, int _incoming, MemoryAddress _user_data) -> {
            try {
                return (Addressable)(MemoryAddress)constants$582.GDBusMessageFilterFunction$MH.invokeExact(symbol, (Addressable)_connection, (Addressable)_message, _incoming, (Addressable)_user_data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


