// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface GHookFunc {

    void apply(MemoryAddress data);
    static NativeSymbol allocate(GHookFunc fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(GHookFunc.class, fi, constants$142.GHookFunc$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)V", scope);
    }
    static GHookFunc ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("GHookFunc::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (MemoryAddress _data) -> {
            try {
                constants$142.GHookFunc$MH.invokeExact(symbol, (Addressable)_data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


