// Generated by jextract

package bluez.binding;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface GOptionErrorFunc {

    void apply(MemoryAddress context, MemoryAddress group, MemoryAddress data, MemoryAddress error);
    static NativeSymbol allocate(GOptionErrorFunc fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(GOptionErrorFunc.class, fi, constants$239.GOptionErrorFunc$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V", scope);
    }
    static GOptionErrorFunc ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("GOptionErrorFunc::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (MemoryAddress _context, MemoryAddress _group, MemoryAddress _data, MemoryAddress _error) -> {
            try {
                constants$239.GOptionErrorFunc$MH.invokeExact(symbol, (Addressable)_context, (Addressable)_group, (Addressable)_data, (Addressable)_error);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


